# Generated by Django 6.0.3 on 2026-06-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("name", models.CharField(max_length=50)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=50)),
                ("department", models.CharField(max_length=50)),
                ("designation", models.CharField(max_length=50)),
                ("salary", models.IntegerField()),
            ],
        ),
    ]
